config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated :user do
    root to: "home#index", as: :root
    resources :item, controller: "items", only: [:index, :show] do
      get "result", on: :collection
    end
    resources :rating, controller: 'rating', only: [:create] do
      get "destroyAll", on: :collection
    end

  end

  unauthenticated :user do
    root to: "home#indexAnonymous", as: :root_anonymous
  end

  get "/about", to: "home#about", as: :about

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :ratings
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :ratings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
  
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    rating = current_user.ratings.limit(1)
    if rating.any?
      redirect_to result_item_index_path
    end
  end

  def indexAnonymous
  end

  def about
  end

end

app/controllers/items_controller.rb
class ItemsController < RecommendationController
  
  def index
    #min is defined for User Experience, it will be better if the user search for the minimum items first to see the list of all items
    min = 5
    @verifyMin = min - current_user.ratings.where("ratings.like = ?", "true").limit(min).count
    if @verifyMin == 0 or params[:title] or params[:genre] or params[:company]

      @items = Item.order('id').paginate(page: params[:page], per_page: 12)
      if params[:title]
        @items = @items.where("title ILIKE ?", "%#{params[:title]}%")
      end 
      if params[:genre]
        @items = @items.where("genre ILIKE ?", "%#{params[:genre]}%")
      end 
      if params[:company]
        @items = @items.where("company ILIKE ?", "%#{params[:company]}%")
      end

      if @verifyMin == 0
        recommendations(6)
      end

    else 

      @items = nil
      @recommendations = nil

    end
  end

  def show
    @item = Item.find(params[:id])
    rating = Rating.where(user_id: current_user.id, item_id: params[:id])
    if rating.none? == false
      if rating[0].like == true
        @disableLikeButton = true
        @disableDislikeButton = false
      else
        @disableLikeButton = false
        @disableDislikeButton = true
      end 
    else
      @disableLikeButton = false
      @disableDislikeButton = false
    end 
    render :layout => false
  end

  def result
    recommendations(12)
    @newItems = Item.limit(10).order('id desc')
  end

end

app/controllers/rating_controller.rb
class RatingController < ApplicationController
  
  def create
    @rating = Rating.where(user_id: current_user.id, item_id: params[:item_id])

    #if doesnt exists any rating from this user for that item, create a new one
    if @rating.none? == true
      @rating = Rating.new()
      @rating.user_id = current_user.id
       @rating.item_id = params[:item_id]
      @rating.like = params[:like]
      @rating.save()
    else
    #if exists a rating from this user for that item, just change the like
      @rating[0].like = params[:like]
      @rating[0].save()
    end
    @like = params[:like] #to be used on create.js.erb
    respond_to do |format|
      format.js
    end
  end

  def destroyAll
    if current_user.ratings.empty?
      redirect_to item_index_path
    else
      if params[:delete] == "true"
        @rating = Rating.where(user_id: current_user.id)
        @rating.destroy_all
        redirect_to item_index_path
      elsif params[:delete] == "false"
        redirect_to item_index_path
      end
    end
  end
 
end

app/controllers/recommendation_controller.rb
class RecommendationController < ApplicationController

  def recommendations(howMany)
    @recommendations = []
    @itemsLike = []
    @itemsDontLike = []
    similarUsers = []
    counts = Hash.new(0)

    current_user.ratings.each do |r|
      if r.like == true
        @itemsLike.append(r.item)
      else
        @itemsDontLike.append(r.item)
      end
    end

    @itemsLike.each do |s|
      s.ratings.each do |r|
        if r.like == true
          similarUsers.append(r.user)
        end
      end
    end

    similarUsers.each { |similarUsers| counts[similarUsers] += 1 }
    counts = counts.sort()
    counts.delete(current_user)

    while (@recommendations.length < howMany and counts.empty? == false)
      counts.first()[0].ratings.each do |r|
        if @recommendations.length == howMany
          break
        end

        item = r.item
        if @itemsLike.empty? == false
          next if @itemsLike.include? item
        end
        if @itemsDontLike.empty? == false
          next if @itemsDontLike.include? item
        end

        if @recommendations.empty? == false
          next if @recommendations.include? item
        end

        @recommendations.append(item)
        
      end
      counts.shift()
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/about.html.erb
<h2 class="about is-size-1-touch"> About the project: </h2>
<p class="is-size-2-touch">Using <a href="https://en.wikipedia.org/wiki/Collaborative_filtering" target="_blank">collaborative filtering</a>, this <a href="https://en.wikipedia.org/wiki/Recommender_system" target="_blank">recommendation system</a> is builded on Ruby on Rails.</p>
<p class="is-size-2-touch">As example was used series that were extracted using a web crawler made in Scrapy to get every single serie from 1980 to today from IMDB. (01 march 2019)</p>
<br/>
<p class="is-size-2-touch">You can find more about this project in: <a href="https://github.com/raicg" target="_blank">RaiCG Github Page</a></p>

app/views/home/index.html.erb
<h2 class="instructions is-size-2-touch">Instructions:</h2>
<p class="is-size-3-touch">On the upside menu, select Recommendations and then New Recommendations;</p>
<p class="is-size-3-touch">After that you need to search for your favorites items;
<p class="is-size-3-touch">Then click on the desired item and use the buttons on the new opened page to make your rating.</p>

<p class="is-size-3-touch">The more items you evaluated, the better will be the recommendations.</p>

app/views/home/indexAnonymous.html.erb
<div class="column is-12">
  <p class="is-size-5-desktop is-size-2-touch">You need to login to use the Recommendation System</p>
</div>
<br/>
<div class="column is-8 is-offset-2">
  <%= link_to "LOGIN", new_user_session_path, class: "button is-normal is-size-2-touch is-outlined is-white" %>
</div>
<br/>
<div class="column is-8 is-offset-2">
  <%= link_to "REGISTER", new_user_registration_path, class: "button is-normal is-size-2-touch is-outlined is-white" %>
</div>

app/views/items/_item.html.erb
<div class="column is-one-third-desktop is-half-tablet is-half-mobile">    
  <a href="<%= item_path(item.id) %>" data-featherlight="iframe" data-featherlight-iframe-height="545px" data-featherlight-iframe-width="500" data-featherlight-after-close="$(function(){ if($('div.search').length == 0){ $('div.recommendations').load(location.href + ' div.recommendations')} else{ window.location.href='<%= item_index_path %>' }});">

    <% if item.image != nil %>    
      <img src="<%= item.image %>" height="180" width="130" />
    <% else %>
      <img src="<%= image_url('default-image.png') %>" height="180" width="130" />
    <% end %>

    <p class="item is-5 is-size-4-touch"><%= item.title %></p>

  </a>
</div>

app/views/items/_search.html.erb
<div class="column is-10 is-offset-1-desktop">
  <%= form_tag(item_index_path, method: :get) do %>
    <div class="field has-addons">
      <div class="control is-expanded">
        <%= text_field_tag :title, nil, class: " is-size-2-touch is-size-4-desktop", placeholder: "Title" %>
      </div>

        
      <div class="control is-expanded">
        <%= text_field_tag :company, nil, placeholder: "Company", class: " is-size-2-touch is-size-4-desktop"  %>
      </div>

      <select name="genre" id="genre" class="is-size-7-touch is-size-7-desktop">
        <option value="">ALL</option>
        <option value="Action">Action</option>
        <option value="Adventure">Adventure</option>
        <option value="Animation">Animation</option>
        <option value="Biography">Biography</option>
        <option value="Comedy">Comedy</option>
        <option value="Crime">Crime</option>
        <option value="Documentary">Documentary</option>
        <option value="Drama">Drama</option>
        <option value="Family">Family</option>
        <option value="Fantasy">Fantasy</option>
        <option value="Game-Show">Game-Show</option>
        <option value="History">History</option>
        <option value="Horror">Horror</option>
        <option value="Music">Music</option>
        <option value="Mystery">Mystery</option>
        <option value="News">News</option>
        <option value="Reality-TV">Reality-TV</option>
        <option value="Romance">Romance</option>
        <option value="Sci-Fi">Sci-Fi</option>
        <option value="Short">Short</option>
        <option value="Sport">Sport</option>
        <option value="Talk-Show">Talk-Show</option>
        <option value="Thriller">Thriller</option>
        <option value="War">War</option>
        <option value="Western">Western</option>
      </select>

      <div class="control">
        <%= submit_tag 'Search', class: "button is-white is-outlined is-small is-size-5-touch is-size-7-desktop"%>
      </div>
    </div>
  <% end %>
</div>
<hr class="line-search"/>

app/views/items/index.html.erb
<div class="search columns is-desktop is-tablet is-mobile">
  <%= render "search" %>
</div>

<hr class="search"/>

<br/>

<% if @items != nil %>

  <div class="recommendations">
    <% if @recommendations != nil %>
      <% if @recommendations.empty? == false %>
        <h2 class="suggestions is-size-2-touch">Suggestions:</h2>
        <div class="columns is-multiline is-desktop is-tablet is-mobile">
          <%= render @recommendations %>
        </div>
        <hr class="list"/>
      <% end %>
    <% end %>
  </div>

  <h2 class="all-the-items is-size-2-touch">All the items:</h2>
  <div class="items columns is-multiline is-desktop is-tablet is-mobile">
    <%= render @items %>
  </div>
  
  <br/>
  
  <div class="pages">
    <%= will_paginate @items %>
  </div>
  
<% else %>
  <br/><br/>
  <h2 class="is-size-2-touch">Search for <%= @verifyMin %> favorite items first.</h2>
  <br/>

<% end %>

app/views/items/result.html.erb
<div class="recommendations">
  <% if @recommendations.any? %>
    <h2 class="result-recommendations is-size-2-touch">Recommendations:</h2>
    <br/>
    <div class="items itemsRecommendation columns is-desktop is-tablet is-mobile">

      <a class="move-scroll-left" onClick="scrollDiv('recommendations', -100)"><i class="fas fa-3x fa-angle-double-left"></i></a>
      <%= render @recommendations %>
      <a class="move-scroll-right" onClick="scrollDiv('recommendations', 100)"><i class="fas fa-3x fa-angle-double-right"></i></a>

    </div>
  <% end %>

  <% if @itemsLike.any? %>
    <hr class="result"/>

    <h2 class="result is-size-2-touch">Items that you like:</h2>
    <br/>
    <div class="items itemsLike columns is-desktop is-tablet is-mobile">
    
      <a class="move-scroll-left" onClick="scrollDiv('itemsLike', -100)"><i class="fas fa-3x fa-angle-double-left"></i></a>
      <%= render @itemsLike %>
      <a class="move-scroll-right" onClick="scrollDiv('itemsLike', 100)"><i class="fas fa-3x fa-angle-double-right"></i></a>
   
    </div>
  <% end %>

  <% if @itemsDontLike.any? %>
    <hr class="result"/>

    <h2 class="result is-size-2-touch">Items that you don't like:</h2>
    <br/>
    <div class="items itemsDontLike columns is-desktop is-tablet is-mobile">
    
      <a class="move-scroll-left" onClick="scrollDiv('itemsDontLike', -100)"><i class="fas fa-3x fa-angle-double-left"></i></a>
      <%= render @itemsDontLike %>
      <a class="move-scroll-right" onClick="scrollDiv('itemsDontLike', 100)"><i class="fas fa-3x fa-angle-double-right"></i></a>

    </div>
  <% end %>

  <% if @newItems.any? %>
    <hr class="result"/>

    <h2 class="result is-size-2-touch">New items:</h2>
    <br/>
    <div class="items newItems columns is-desktop is-tablet is-mobile">
    
      <a class="move-scroll-left" onClick="scrollDiv('newItems', -100)"><i class="fas fa-3x fa-angle-double-left"></i></a>
      <%= render @newItems %>
      <a class="move-scroll-right" onClick="scrollDiv('newItems', 100)"><i class="fas fa-3x fa-angle-double-right"></i></a>
   
    </div>
  <% end %>
</div>


<%= javascript_include_tag 'result', 'data-turbolinks-track': 'reload' %>

app/views/items/show.html.erb
<!DOCTYPE html>
<html class="details">
  <head>
    <title>Recommendation System</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'details', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/all.min.css" rel="stylesheet">
  </head>
  <body>
    <center>
      <div class="details">

        <% if @item.image != nil %>
          <img src="<%= @item.image %>"/>
        <% else %>
          <img src="<%= image_url('default-image.png') %>"/>
        <% end %>

        <h1><b><%= @item.title %></b></h1>
        <p><%= @item.genre %></p>

        <% if @item.yearLastSeason != nil %>
          <label>Last Season:</label> <span><%= @item.yearLastSeason %></span >
        <% end %>
	  <br/><br/>

        
        <% if @item.company != nil %>
          <label>Productor Companies:</label> 
          <br/>
          <label><%= @item.company %></label>
        <% end %>

        <br/><br/>
        <div class="columns is-multiline is-desktop is-tablet is-mobile create">

          <div class="column is-2 is-offset-4">  
            <%= button_to rating_index_path(item_id: @item.id, like: true, format: "js"), remote: true, :disabled => @disableLikeButton, :id => "like" do %>
              <i class="far fa-thumbs-up fa-3x"></i>          
            <% end %>
          </div>
          <div class="column is-2">  
            <%= button_to rating_index_path(item_id: @item.id, like: false, format: "js"), remote: true, :disabled => @disableDislikeButton, :id => "dislike" do %>
              <i class="far fa-thumbs-down fa-3x"></i>          
            <% end %>
          </div>
        </div>
      </div>
    </center>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recommendation System</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <link rel="manifest" href="/manifest.json" />
<meta name="apple-mobile-web-app-capable" content="yes"></head>

  <body>
    <%= render "shared/navbar" %>
    <div class="hero-body">
      <div class="container has-text-centered">
        <div class="section">
          <div class="row columns">
            <div class="column is-10 is-offset-1">
              <div class="card large box">
                <div class="card-content">
                  <div class="content">
                    <%= yield %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/rating/create.js.erb
$(document).ready(function(){
  if (<%= @like %> == true) {
    $("button#like").prop('disabled', true);
    $("button#dislike").removeAttr("disabled");
  } else {
    $("button#like").removeAttr("disabled");
    $("button#dislike").prop('disabled', true);
  }
});

app/views/rating/destroyAll.html.erb
<h2 class="destroyAll is-size-1-touch">Do you want to delete your ratings?</h2>
<%= form_tag(destroyAll_rating_index_path, method: :get) do %>  
  <input type="radio" name="delete" value="true" checked"><label class=" is-size-2-touch"> Yes </label>
  <br/>
  <input type="radio" name="delete" value="false"><label class="is-size-2-touch"> No </label>
  <br/>
  <br/>
  <%= submit_tag 'Continue', class: "button is-white is-outlined is-normal is-size-3-touch"%>
<% end %>

app/views/shared/_navbar.html.erb
<section class="hero">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar is-mobile is-desktop">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item is-size-3-touch" href="/">
            Recommendation System
          </a>
          <a class="navbar-burger">
            <i class="menu fa fa-bars fa-3x has-text-white-bis"></i>
          </a>
        </div>
        <div id="navbarMenuHero1" class="navbar-menu">
          <div class="navbar-end">
            <%= link_to root_path, class: "navbar-item is-size-3-touch" do %>
              Home
            <% end %>
            <%= link_to about_path, class: "navbar-item is-size-3-touch" do %>
              About
            <% end %>

            <% if user_signed_in? %>
              <div class="navbar-item has-dropdown is-hoverable">
                <div class="navbar-link is-size-3-touch">
                  Recommendations
                </div>
                <div id="moreDropdown" class="navbar-dropdown ">
                
                  <%= link_to destroyAll_rating_index_path, class: "navbar-item is-size-3-touch" do %>
                    <div class="level is-mobile">
                      <div class="level-left">
                        <div class="level-item">
                          <p>
                            <strong>New Recommendations</strong>
                            <br>
                            <small>Get new recommendations of the system</small>
                          </p>
                        </div>
                      </div>
                    </div>
                  <% end %>
                  
                  <%= link_to result_item_index_path, class: "navbar-item is-size-3-touch" do %>
                    <div class="level is-mobile">
                      <div class="level-left">
                        <div class="level-item">
                          <p>
                            <strong>See Recommendations</strong>
                            <br>
                            <small>See what the system recommends for you</small>
                          </p>
                        </div>
                      </div>
                    </div>
                  <% end %>

                </div>
              </div>
              <%= link_to destroy_user_session_path, method: :delete, class: "navbar-item is-size-3-touch" do %>
                Logout
              <% end %>
            <% else %>
              <%= link_to new_user_session_path, class: "navbar-item is-size-3-touch" do %>
                Login
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
  </div>
</section>

<%= javascript_include_tag 'navbar', 'data-turbolinks-track': 'reload' %>